<?php

declare(strict_types=1);
require dirname(__DIR__,2).'/vendor/autoload.php';
use App\Bootstrap\App; use App\Database\Database; use App\Support\Auth; use App\Modules\Subscriptions\SubscriptionPlanRepository; use App\Modules\Subscriptions\SubscriptionRepository; use function App\Support\e;
new App(); $db=Database::connection(); Auth::requireAdmin($db); $plans=(new SubscriptionPlanRepository($db))->all(); $subscriptions=(new SubscriptionRepository($db))->allForAdmin();
ob_start(); ?>
<div class="container py-5"><div class="d-flex justify-content-between align-items-center mb-4"><div><div class="small text-secondary">Dukame administration</div><h1 class="h3 fw-bold mb-0">Subscription overview</h1></div><div class="d-flex gap-2"><a href="/admin/plans" class="btn btn-primary">Manage plans</a><a href="/logout" class="btn btn-outline-dark">Log out</a></div></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="metric-card"><div class="metric-label">Plans</div><div class="metric-value"><?= count($plans) ?></div><div class="metric-meta">Configured plans</div></div></div><div class="col-md-4"><div class="metric-card"><div class="metric-label">Subscriptions</div><div class="metric-value"><?= count($subscriptions) ?></div><div class="metric-meta">Merchant subscriptions</div></div></div><div class="col-md-4"><div class="metric-card"><div class="metric-label">Active / Trial</div><div class="metric-value"><?= count(array_filter($subscriptions,fn($s)=>in_array($s['status'],['active','trial','past_due'],true))) ?></div><div class="metric-meta">Currently usable</div></div></div></div>
<div class="panel"><div class="panel-heading"><div><h2 class="h5 fw-bold mb-1">Recent subscriptions</h2><p class="small text-secondary mb-0">Only merchant subscription metadata is shown here. No payment secrets are exposed.</p></div></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Shop</th><th>Plan</th><th>Status</th><th>Billing</th><th>Owner</th></tr></thead><tbody><?php foreach($subscriptions as $s): ?><tr><td><strong><?= e($s['shop_name']) ?></strong><div class="small text-secondary">/<?= e($s['slug']) ?></div></td><td><?= e($s['plan_name']) ?></td><td><span class="status-badge status-<?= e($s['status']) ?>"><?= e(ucwords(str_replace('_',' ',$s['status']))) ?></span></td><td><?= e($s['billing_interval']) ?></td><td><?= e($s['owner_phone']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php $content=ob_get_clean(); $title='Admin'; require dirname(__DIR__,2).'/app/Views/layouts/app.php';
