<?php
declare(strict_types=1);
require dirname(__DIR__, 2) . '/vendor/autoload.php';
use App\Bootstrap\App; use App\Database\Database; use App\Modules\Products\ProductRepository; use App\Modules\Shops\ShopRepository; use function App\Support\e; use function App\Support\shop_url;
new App(); $slug=trim((string)($_GET['slug']??'')); $productSlug=trim((string)($_GET['product']??'')); $db=Database::connection();
$stmt=$db->prepare('SELECT id FROM shops WHERE slug=:slug AND status="active" LIMIT 1'); $stmt->execute(['slug'=>$slug]); $shopId=(int)($stmt->fetchColumn()?:0); if(!$shopId){http_response_code(404);exit('Shop not found');}
$shop=(new ShopRepository($db))->find($shopId); $stmt=$db->prepare('SELECT p.*, c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.shop_id=:shop AND p.slug=:slug AND p.status="active" LIMIT 1'); $stmt->execute(['shop'=>$shopId,'slug'=>$productSlug]); $product=$stmt->fetch(); if(!$product){http_response_code(404);exit('Product not found');}
$options=json_decode($product['options_json']??'[]',true)?:[]; $currency=$shop['currency']?:'KES';
ob_start(); ?>
<div class="customer-store customer-product-page"><header class="customer-store-header"><div class="customer-container"><div class="customer-store-top"><a href="<?=e(shop_url($slug))?>" class="customer-back">← <span>Back to shop</span></a><a class="customer-cart" href="/cart?shop=<?=e($slug)?>"><span class="cart-icon">🛒</span><span class="cart-label">Cart</span><b data-cart-count>0</b></a></div></div></header>
<main class="customer-container customer-product-detail"><div class="product-detail-grid"><div class="product-detail-media"><?php if($product['image_path']):?><img src="<?=e($product['image_path'])?>" alt="<?=e($product['name'])?>"><?php else:?><span>◇</span><?php endif;?></div><div class="product-detail-copy"><div class="customer-product-category"><?=e($product['category_name']?:'Product')?></div><h1><?=e($product['name'])?></h1><div class="product-detail-price"><strong><?=e($currency)?> <?=number_format((float)$product['price'],2)?></strong><?php if($product['compare_at_price']):?><del><?=e($currency)?> <?=number_format((float)$product['compare_at_price'],2)?></del><?php endif;?></div>
<?php if(!empty($product['description'])):?><div class="product-description"><p data-description><?=nl2br(e($product['description']))?></p><button type="button" data-read-more>Read more</button></div><?php endif;?>
<?php if($options):?><div class="product-option-group"><label>Choose option</label><div class="product-options" data-option-group><?php foreach($options as $i=>$option):?><button type="button" class="product-option" data-option value="<?=e($option)?>"><?=e($option)?></button><?php endforeach;?></div></div><?php endif;?>
<div class="product-quantity"><label>Quantity</label><div class="quantity-control"><button type="button" data-qty-minus>−</button><input value="1" inputmode="numeric" data-qty><button type="button" data-qty-plus>+</button></div></div>
<button class="customer-primary-action" type="button" data-detail-add data-product-id="<?= (int)$product['id']?>" data-product-name="<?=e($product['name'])?>" data-product-price="<?=e((string)$product['price'])?>" data-product-image="<?=e((string)$product['image_path'])?>" data-product-slug="<?=e($product['slug'])?>">Add to cart</button>
<p class="product-no-account">No account needed. Add items and order when you're ready.</p></div></div></main><div class="customer-cart-toast" data-floating-cart hidden><div><small>Cart</small><strong><span data-cart-count>0</span> items · <span data-cart-total>0</span></strong></div><a href="/cart?shop=<?=e($slug)?>">View cart →</a></div></div>
<script>window.DUKAME_STORE=<?=json_encode(['slug'=>$slug,'currency'=>$currency],JSON_UNESCAPED_SLASHES)?>; window.DUKAME_PRODUCT_OPTIONS=<?=json_encode($options,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script>
<?php $content=ob_get_clean();$title=$product['name'].' · '.$shop['name'];require dirname(__DIR__,2).'/app/Views/layouts/customer.php';
