<?php
declare(strict_types=1);
$root = dirname(__DIR__, 5); require $root . '/vendor/autoload.php';
use App\Bootstrap\App; use App\Database\Database; use App\Modules\Orders\OrderRepository; use App\Modules\Orders\OrderService; use App\Modules\Shops\ShopRepository; use App\Support\Auth; use App\Support\Csrf; use App\Support\Session; use function App\Support\e;
new App(); $db=Database::connection(); $merchant=Auth::requireMerchant($db); $shopId=(int)$merchant['id']; $shop=(new ShopRepository($db))->find($shopId); $repo=new OrderRepository($db);
if($_SERVER['REQUEST_METHOD']==='POST'){ if(!Csrf::verify($_POST['_csrf']??null)){Session::flash('error','Your form session expired. Please try again.');}else{try{(new OrderService($db))->updateStatus((int)($_POST['id']??0),$shopId,(string)($_POST['status']??''));Session::flash('success','Order status updated.');}catch(\InvalidArgumentException|\RuntimeException $e){Session::flash('error',$e->getMessage());}} header('Location: /orders'); exit; }
$status=trim((string)($_GET['status']??'')); $orders=$repo->allForShop($shopId,$status!==''?$status:null); $counts=$repo->countByStatus($shopId); $merchantShop=$shop; $merchantSection='orders'; $pageStyles=['/assets/css/pages/orders.css']; ob_start();
?>
<div class="merchant-shell orders-page"><?php require $root.'/app/Views/components/merchant-sidebar.php'; ?><main class="merchant-main">
<div class="merchant-topbar"><div><div class="small text-secondary">Sales</div><h1 class="h3 fw-bold mb-0">Orders</h1></div></div>
<?php require $root.'/app/Views/components/alert.php'; ?>
<div class="row g-3 mb-4"><?php foreach([['pending','New'],['confirmed','Confirmed'],['preparing','Preparing'],['ready','Ready']] as [$key,$label]): ?><div class="col-6 col-xl-3"><a class="orders-summary-card <?=$status===$key?'active':''?>" href="/orders?status=<?=e($key)?>"><div class="small text-secondary"><?=e($label)?></div><div class="h3 fw-bold mb-0 mt-1"><?=number_format($counts[$key])?></div></a></div><?php endforeach; ?></div>
<section class="panel"><div class="orders-filter-bar"><div><h2 class="h5 fw-bold mb-1">Order list</h2><p class="small text-secondary mb-0">Orders placed by customers through your store.</p></div><div class="orders-filter-tabs"><?php foreach([''=>'All','pending'=>'New','confirmed'=>'Confirmed','preparing'=>'Preparing','ready'=>'Ready','delivered'=>'Delivered'] as $key=>$label): ?><a href="/orders<?=$key!==''?'?status='.e($key):''?>" class="btn btn-sm <?=$status===$key?'btn-dark':'btn-outline-dark'?>"><?=e($label)?></a><?php endforeach; ?></div></div>
<?php if(!$orders): ?><div class="empty-state"><div class="empty-icon">▤</div><h3 class="h5 fw-bold">No orders yet</h3><p class="text-secondary mb-0">Customer orders will appear here as soon as your store starts receiving them.</p></div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0 orders-table"><thead><tr><th>Order</th><th>Customer</th><th>Fulfilment</th><th>Total</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody><?php foreach($orders as $order): ?><tr><td><a class="order-row-link fw-bold" href="/orders/view?id=<?=(int)$order['id']?>">#<?=e($order['order_number'])?></a></td><td><div class="fw-semibold"><?=e($order['customer_name'])?></div><div class="small text-secondary"><?=e($order['customer_phone'])?></div></td><td><span class="small fw-semibold"><?=e($order['fulfillment_method']==='pickup'?'Pickup':'Delivery')?></span><?php if($order['delivery_zone_name']): ?><div class="small text-secondary"><?=e($order['delivery_zone_name'])?></div><?php endif; ?></td><td class="order-total"><?=e($order['currency'])?> <?=number_format((float)$order['total'],2)?></td><td><span class="status-badge status-<?=e($order['status'])?>"><?=e(ucfirst($order['status']))?></span></td><td class="order-date"><?=e(date('d M Y, H:i',strtotime($order['created_at'])))?></td><td><a href="/orders/view?id=<?=(int)$order['id']?>" class="btn btn-sm btn-outline-dark">View</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
</main></div>
<?php $content=ob_get_clean(); $title='Orders'; $merchantLayout=true; require $root.'/app/Views/layouts/app.php';
