<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/vendor/autoload.php';
use App\Bootstrap\App; use App\Database\Database; use App\Modules\Platform\PlatformRepository; use App\Support\PlatformAuth; use function App\Support\e;
new App(); $db=Database::connection(); $platformUser=PlatformAuth::requireAdmin($db); $repo=new PlatformRepository($db);
function platformStatus(?string $status): string { return match($status){ 'active','paid'=>'status-active','trial'=>'status-trial','pending','past_due'=>'status-past_due','failed','expired','cancelled','suspended','refunded'=>'status-expired',default=>'status-draft'}; }
$search=trim((string)($_GET['search']??'')); $status=trim((string)($_GET['status']??'')); $plan=trim((string)($_GET['plan']??'')); $page=max(1,(int)($_GET['page']??1)); $result=$repo->subscriptions($search,$status,$plan,$page,20);
$plans=$db->query("SELECT slug,name FROM subscription_plans ORDER BY sort_order ASC,id ASC")->fetchAll();
ob_start(); ?>
<section class="platform-panel"><div class="platform-panel-head"><div><h2>Subscriptions</h2><p>Merchant subscription state, billing period and plan across the platform.</p></div><span class="platform-muted"><?= number_format($result['total']) ?> total</span></div>
<form class="platform-search" method="get"><div class="row g-2 align-items-end"><div class="col-lg-5"><label class="form-label small fw-semibold">Search</label><input class="form-control" name="search" value="<?= e($search) ?>" placeholder="Shop, merchant or phone"></div><div class="col-lg-3"><label class="form-label small fw-semibold">Status</label><select class="form-select" name="status"><option value="">All</option><?php foreach(['trial','active','past_due','expired','cancelled'] as $x): ?><option value="<?= e($x) ?>" <?= $status===$x?'selected':'' ?>><?= e(ucwords(str_replace('_',' ',$x))) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><label class="form-label small fw-semibold">Plan</label><select class="form-select" name="plan"><option value="">All plans</option><?php foreach($plans as $p): ?><option value="<?= e($p['slug']) ?>" <?= $plan===$p['slug']?'selected':'' ?>><?= e($p['name']) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><button class="btn btn-primary w-100">Filter</button></div></div></form>
<div class="table-responsive"><table class="table platform-table align-middle mb-0"><thead><tr><th>Merchant / Shop</th><th>Plan</th><th>Status</th><th>Interval</th><th>Current period</th><th>Created</th></tr></thead><tbody><?php if(!$result['items']): ?><tr><td colspan="6"><div class="platform-empty">No subscriptions match your filters.</div></td></tr><?php endif; ?><?php foreach($result['items'] as $r): ?><tr><td><div class="fw-semibold"><?= e($r['shop_name']) ?></div><div class="platform-muted"><?= e(trim(($r['first_name']??'').' '.($r['last_name']??''))) ?> · <?= e($r['phone']) ?></div></td><td><div class="fw-semibold"><?= e($r['plan_name']) ?></div><div class="platform-muted"><?= e($r['currency']) ?> <?= number_format((float)($r['billing_interval']==='annual'?$r['annual_price']:$r['monthly_price']),2) ?></div></td><td><span class="status-badge <?= e(platformStatus($r['status'])) ?>"><?= e(ucwords(str_replace('_',' ',(string)$r['status']))) ?></span></td><td><?= e(ucfirst($r['billing_interval'])) ?></td><td class="platform-muted"><?= $r['current_period_start']?e(date('d M Y',strtotime($r['current_period_start']))):'—' ?> to <?= $r['current_period_end']?e(date('d M Y',strtotime($r['current_period_end']))):'—' ?></td><td class="platform-muted"><?= e(date('d M Y',strtotime($r['created_at']))) ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php if($result['pages']>1): ?><div class="p-3 border-top d-flex justify-content-between"><span class="platform-muted">Page <?= $result['page'] ?> of <?= $result['pages'] ?></span><div class="d-flex gap-1"><?php if($result['page']>1): ?><a class="btn btn-sm btn-light border" href="?<?= http_build_query(['search'=>$search,'status'=>$status,'plan'=>$plan,'page'=>$result['page']-1]) ?>">Previous</a><?php endif; ?><?php if($result['page']<$result['pages']): ?><a class="btn btn-sm btn-light border" href="?<?= http_build_query(['search'=>$search,'status'=>$status,'plan'=>$plan,'page'=>$result['page']+1]) ?>">Next</a><?php endif; ?></div></div><?php endif; ?></section>
<?php $content=ob_get_clean(); $title='Subscriptions'; $platformSection='subscriptions'; require dirname(__DIR__,2).'/app/Views/layouts/platform.php';
