<?php
use function App\Support\e;
$brand=require dirname(__DIR__,2).'/config/branding.php';
$plans=(new \App\Modules\Subscriptions\SubscriptionPlanRepository(\App\Database\Database::connection()))->publicPlans();
$features=[['01','Create your shop','Choose your shop name and get a shareable storefront link.'],['02','Add what you sell','Add products, prices and photos without complicated setup.'],['03','Share and receive orders','Send your shop link to customers and manage orders from one place.']];
ob_start(); ?>
<section class="hero-section"><div class="container py-5"><div class="row align-items-center g-5 py-lg-5"><div class="col-lg-7"><span class="eyebrow">ONLINE COMMERCE FOR GROWING BUSINESSES</span><h1 class="hero-title mt-3"><?=\App\Support\e($brand['tagline'])?>.</h1><p class="hero-copy mt-4">Create a beautiful online shop, share one simple link with customers, and build your business without making shopping complicated.</p><div class="d-flex flex-wrap gap-2 mt-4"><a href="/register" class="btn btn-primary btn-lg px-4">Create your shop</a><a href="/login" class="btn btn-light btn-lg px-4 border">Merchant login</a></div><div class="trust-row mt-4"><span>✓ No customer account required</span><span>✓ Mobile-first</span><span>✓ M-Pesa ready</span></div></div><div class="col-lg-5"><div class="commerce-mockup"><div class="mockup-topbar"><div class="d-flex align-items-center gap-2"><span class="mock-dot"></span><span class="mock-dot"></span><span class="mock-dot"></span></div><span class="small text-secondary">Your shop</span></div><div class="mockup-store"><div class="d-flex justify-content-between align-items-start"><div><div class="fw-bold fs-5">Your Store</div><div class="small text-secondary">A simple storefront</div></div><div class="cart-pill">🛒 2</div></div><div class="search-placeholder mt-4">Search products...</div><div class="row g-3 mt-2"><div class="col-6"><div class="product-mock"><div class="product-image gradient-one"></div><div class="small fw-semibold mt-2">Product One</div><div class="small text-secondary">KSh 2,500</div></div></div><div class="col-6"><div class="product-mock"><div class="product-image gradient-two"></div><div class="small fw-semibold mt-2">Product Two</div><div class="small text-secondary">KSh 3,500</div></div></div></div><div class="mock-cart mt-4"><span>2 items</span><strong>KSh 6,000 </strong></div></div></div></div></div></div></section>
<section class="py-5"><div class="container py-lg-4"><div class="section-heading mb-5"><span class="eyebrow">HOW IT WORKS</span><h2 class="fw-bold mt-2">From idea to online shop</h2><p class="text-secondary mb-0">Everything starts with a few simple steps.</p></div><div class="row g-4"><?php foreach($features as [$number,$heading,$text]): ?><div class="col-md-4"><article class="feature-card h-100"><div class="feature-icon"><?=\App\Support\e($number)?></div><h3 class="h5 fw-bold mt-4"><?=\App\Support\e($heading)?></h3><p class="text-secondary mb-0"><?=\App\Support\e($text)?></p></article></div><?php endforeach; ?></div></div></section>
<section class="py-5 bg-white"><div class="container py-lg-4"><div class="section-heading mb-5"><span class="eyebrow">SIMPLE PRICING</span><h2 class="fw-bold mt-2">Choose a plan that grows with your shop</h2><p class="text-secondary mb-0">Plans, prices and limits are configured in Dukame. Start with a trial and upgrade when your catalogue grows.</p><div class="pricing-toggle mt-4"><button type="button" class="btn btn-primary btn-sm" data-pricing-interval="monthly">Monthly</button><button type="button" class="btn btn-light border btn-sm" data-pricing-interval="annual">Annual</button></div></div><div class="row g-4 align-items-stretch"><?php foreach($plans as $plan): ?><div class="col-md-6 col-xl-4"><article class="pricing-card h-100 <?= !empty($plan['is_featured']) ? 'pricing-card-featured' : '' ?>"><?php if(!empty($plan['is_featured'])): ?><span class="pricing-popular">Popular</span><?php endif; ?><h3 class="h5 fw-bold"><?= e($plan['name']) ?></h3><p class="small text-secondary min-h-plan"><?= e($plan['description'] ?? '') ?></p><div class="pricing-price"><span data-monthly="<?= e((string)$plan['monthly_price']) ?>" data-annual="<?= e((string)$plan['annual_price']) ?>"><?= e($plan['currency']) ?> <?= number_format((float)$plan['monthly_price'],0) ?></span><small data-price-label>/ month</small></div><?php if((int)$plan['trial_days']>0): ?><div class="small fw-semibold text-primary mb-3"><?= (int)$plan['trial_days'] ?>-day free trial</div><?php endif; ?><div class="pricing-features"><?php foreach($plan['features'] as $feature): ?><div class="d-flex gap-2 align-items-start"><span class="text-success fw-bold"><?= !empty($feature['enabled']) ? '✓' : '×' ?></span><span><?= e($feature['feature_name']) ?><?php if(!empty($feature['enabled']) && $feature['limit_value'] !== null): ?> <span class="text-secondary">(<?= (int)$feature['limit_value'] < 0 ? 'Unlimited' : (int)$feature['limit_value'] ?>)</span><?php endif; ?></span></div><?php endforeach; ?></div><a href="/register" class="btn <?= !empty($plan['is_featured']) ? 'btn-primary' : 'btn-outline-dark' ?> w-100 mt-4">Start with <?= e($plan['name']) ?></a></article></div><?php endforeach; ?></div></div></section>
<script>document.addEventListener('DOMContentLoaded',function(){const buttons=document.querySelectorAll('[data-pricing-interval]');const prices=document.querySelectorAll('[data-monthly][data-annual]');buttons.forEach(function(button){button.addEventListener('click',function(){const annual=button.dataset.pricingInterval==='annual';buttons.forEach(function(b){b.classList.toggle('btn-primary',b===button);b.classList.toggle('btn-light',b!==button);});prices.forEach(function(p){const value=Number(annual?p.dataset.annual:p.dataset.monthly);p.textContent=(p.textContent.match(/^[A-Z]{3}/)?.[0]||'KES')+' '+new Intl.NumberFormat().format(Math.round(value));const label=p.parentElement.querySelector('[data-price-label]');if(label)label.textContent=annual?'/ year':'/ month';});});});});</script>
<section class="py-5"><div class="container py-4"><div class="cta-card"><div><span class="eyebrow eyebrow-light">READY WHEN YOU ARE</span><h2 class="fw-bold text-white mt-2 mb-2">Put your business online.</h2><p class="text-white-50 mb-0">Start with the basics and grow as your shop grows.</p></div><a href="/register" class="btn btn-light btn-lg px-4">Get started</a></div></div></section>
<?php $content=ob_get_clean(); $title=$brand['name']; require __DIR__.'/layouts/app.php';

