<?php
declare(strict_types=1);

$root = dirname(__DIR__, 4);
require $root.'/vendor/autoload.php';
use App\Bootstrap\App; use App\Database\Database; use App\Modules\Platform\PlatformRepository; use App\Support\PlatformAuth; use function App\Support\e;
new App(); $db=Database::connection(); $platformUser=PlatformAuth::requireAdmin($db); $repo=new PlatformRepository($db);
function platformStatus(?string $status): string { return match($status){ 'active','paid'=>'status-active','trial'=>'status-trial','pending','past_due'=>'status-past_due','failed','expired','cancelled','suspended','refunded'=>'status-expired',default=>'status-draft'}; }
$search=trim((string)($_GET['search']??'')); $status=trim((string)($_GET['status']??'')); $payment=trim((string)($_GET['payment_status']??'')); $page=max(1,(int)($_GET['page']??1)); $result=$repo->orders($search,$status,$payment,$page,20);
ob_start(); ?>
<section class="platform-panel"><div class="platform-panel-head"><div><h2>Orders</h2><p>Platform-wide order activity across merchant shops.</p></div><span class="platform-muted"><?= number_format($result['total']) ?> total</span></div>
<form class="platform-search" method="get"><div class="row g-2 align-items-end"><div class="col-lg-5"><label class="form-label small fw-semibold">Search</label><input class="form-control" name="search" value="<?= e($search) ?>" placeholder="Order number, customer, shop or phone"></div><div class="col-lg-2"><label class="form-label small fw-semibold">Order status</label><select class="form-select" name="status"><option value="">All</option><?php foreach(['pending','confirmed','preparing','ready','delivered','cancelled','rejected'] as $x): ?><option value="<?= e($x) ?>" <?= $status===$x?'selected':'' ?>><?= e(ucwords($x)) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><label class="form-label small fw-semibold">Payment</label><select class="form-select" name="payment_status"><option value="">All</option><?php foreach(['pending','paid','failed','refunded'] as $x): ?><option value="<?= e($x) ?>" <?= $payment===$x?'selected':'' ?>><?= e(ucfirst($x)) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><button class="btn btn-primary w-100">Filter</button></div></div></form>
<div class="table-responsive"><table class="table platform-table align-middle mb-0"><thead><tr><th>Order</th><th>Shop</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Date</th></tr></thead><tbody>
<?php if(!$result['items']): ?><tr><td colspan="7"><div class="platform-empty">No orders match your filters.</div></td></tr><?php endif; ?>
<?php foreach($result['items'] as $r): ?><tr><td><div class="fw-semibold"><?= e($r['order_number']) ?></div><div class="platform-muted">#<?= (int)$r['id'] ?></div></td><td><div class="fw-semibold"><?= e($r['shop_name']) ?></div><div class="platform-muted">/<?= e($r['slug']) ?></div></td><td><div class="fw-semibold"><?= e($r['customer_name']) ?></div><div class="platform-muted"><?= e($r['customer_phone']) ?></div></td><td class="fw-semibold"><?= e($r['currency']) ?> <?= number_format((float)$r['total'],2) ?></td><td><span class="status-badge <?= e(platformStatus($r['payment_status'])) ?>"><?= e(ucfirst($r['payment_status'])) ?></span><div class="platform-muted"><?= e(str_replace('_',' ',(string)$r['payment_method'])) ?></div></td><td><span class="status-badge <?= e(platformStatus($r['status'])) ?>"><?= e(ucwords(str_replace('_',' ',(string)$r['status']))) ?></span></td><td class="platform-muted"><?= e(date('d M Y H:i',strtotime((string)$r['created_at']))) ?></td></tr><?php endforeach; ?>
</tbody></table></div>
<?php if($result['pages']>1): ?><div class="p-3 border-top d-flex justify-content-between"><span class="platform-muted">Page <?= $result['page'] ?> of <?= $result['pages'] ?></span><div class="d-flex gap-1"><?php if($result['page']>1): ?><a class="btn btn-sm btn-light border" href="?<?= http_build_query(['search'=>$search,'status'=>$status,'payment_status'=>$payment,'page'=>$result['page']-1]) ?>">Previous</a><?php endif; ?><?php if($result['page']<$result['pages']): ?><a class="btn btn-sm btn-light border" href="?<?= http_build_query(['search'=>$search,'status'=>$status,'payment_status'=>$payment,'page'=>$result['page']+1]) ?>">Next</a><?php endif; ?></div></div><?php endif; ?></section>
<?php $content=ob_get_clean(); $title='Orders'; $platformSection='orders'; require $root.'/app/Views/layouts/platform.php';
