<?php
declare(strict_types=1);

$root = dirname(__DIR__, 4);
require $root.'/vendor/autoload.php';
use App\Bootstrap\App; use App\Database\Database; use App\Modules\Platform\PlatformRepository; use App\Support\PlatformAuth; use function App\Support\e;
new App(); $db=Database::connection(); $platformUser=PlatformAuth::requireAdmin($db); $repo=new PlatformRepository($db);
function platformStatus(?string $status): string { return match($status){ 'active','paid'=>'status-active','trial'=>'status-trial','pending','past_due'=>'status-past_due','failed','expired','cancelled','suspended','refunded'=>'status-expired',default=>'status-draft'}; }
$search=trim((string)($_GET['search']??'')); $status=trim((string)($_GET['status']??'')); $provider=trim((string)($_GET['provider']??'')); $page=max(1,(int)($_GET['page']??1)); $result=$repo->payments($search,$status,$provider,$page,20);
ob_start(); ?><section class="platform-panel"><div class="platform-panel-head"><div><h2>Subscription payments</h2><p>Payments made by merchants to Dukame for their subscriptions.</p></div><span class="platform-muted"><?= number_format($result['total']) ?> total</span></div>
<form class="platform-search" method="get"><div class="row g-2 align-items-end"><div class="col-lg-6"><label class="form-label small fw-semibold">Search</label><input class="form-control" name="search" value="<?= e($search) ?>" placeholder="Receipt, reference, shop or phone"></div><div class="col-lg-2"><label class="form-label small fw-semibold">Status</label><select class="form-select" name="status"><option value="">All</option><?php foreach(['pending','paid','failed','cancelled','refunded'] as $x): ?><option value="<?= e($x) ?>" <?= $status===$x?'selected':'' ?>><?= e(ucfirst($x)) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><label class="form-label small fw-semibold">Provider</label><select class="form-select" name="provider"><option value="">All</option><option value="mpesa" <?= $provider==='mpesa'?'selected':'' ?>>M-Pesa</option></select></div><div class="col-lg-2"><button class="btn btn-primary w-100">Filter</button></div></div></form>
<div class="table-responsive"><table class="table platform-table align-middle mb-0"><thead><tr><th>Date</th><th>Merchant / Shop</th><th>Plan</th><th>Amount</th><th>Provider</th><th>Status</th><th>Receipt</th></tr></thead><tbody><?php if(!$result['items']): ?><tr><td colspan="7"><div class="platform-empty">No subscription payments match your filters.</div></td></tr><?php endif; ?><?php foreach($result['items'] as $r): ?><tr><td class="platform-muted"><?= e(date('d M Y H:i',strtotime($r['created_at']))) ?></td><td><div class="fw-semibold"><?= e($r['shop_name']) ?></div><div class="platform-muted"><?= e(trim(($r['first_name']??'').' '.($r['last_name']??''))) ?> · <?= e($r['phone']) ?></div></td><td><?= e($r['plan_name']??'—') ?><div class="platform-muted"><?= e(ucfirst($r['billing_interval'])) ?></div></td><td class="fw-semibold"><?= e($r['currency']) ?> <?= number_format((float)$r['amount'],2) ?></td><td><?= e(strtoupper($r['provider'])) ?><div class="platform-muted text-truncate" style="max-width:170px" title="<?= e($r['provider_reference']??'') ?>"><?= e($r['provider_reference']??'—') ?></div></td><td><span class="status-badge <?= e(platformStatus($r['status'])) ?>"><?= e(ucfirst($r['status'])) ?></span><div class="platform-muted"><?= e($r['result_description']??'') ?></div></td><td class="fw-semibold"><?= e($r['mpesa_receipt']??'—') ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php if($result['pages']>1): ?><div class="p-3 border-top d-flex justify-content-between"><span class="platform-muted">Page <?= $result['page'] ?> of <?= $result['pages'] ?></span><div class="d-flex gap-1"><?php if($result['page']>1): ?><a class="btn btn-sm btn-light border" href="?<?= http_build_query(['search'=>$search,'status'=>$status,'provider'=>$provider,'page'=>$result['page']-1]) ?>">Previous</a><?php endif; ?><?php if($result['page']<$result['pages']): ?><a class="btn btn-sm btn-light border" href="?<?= http_build_query(['search'=>$search,'status'=>$status,'provider'=>$provider,'page'=>$result['page']+1]) ?>">Next</a><?php endif; ?></div></div><?php endif; ?></section><?php $content=ob_get_clean(); $title='Payments'; $platformSection='payments'; require $root.'/app/Views/layouts/platform.php';
