<?php

declare(strict_types=1);

$root = dirname(__DIR__, 4);
require $root.'/vendor/autoload.php';
use App\Bootstrap\App; use App\Database\Database; use App\Modules\Platform\PlatformRepository; use App\Support\PlatformAuth; use function App\Support\e;
new App(); $db=Database::connection(); $platformUser=PlatformAuth::requireAdmin($db); $repo=new PlatformRepository($db);
$search=trim((string)($_GET['search']??'')); $status=trim((string)($_GET['status']??'')); $page=max(1,(int)($_GET['page']??1)); $result=$repo->shops($search,$status,$page,20);
function shopStatusClass(?string $status): string { return match($status){ 'active'=>'status-active','suspended'=>'status-expired','closed'=>'status-expired',default=>'status-draft'}; }
ob_start(); ?>
<section class="platform-panel">
 <div class="platform-panel-head"><div><h2>Shops</h2><p>Every merchant storefront, its owner, catalogue size and subscription state.</p></div><span class="platform-muted"><?= number_format($result['total']) ?> total</span></div>
 <form class="platform-search" method="get"><div class="row g-2 align-items-end"><div class="col-lg-7"><label class="form-label small fw-semibold">Search</label><input class="form-control" name="search" value="<?= e($search) ?>" placeholder="Shop name, slug, owner or phone"></div><div class="col-lg-3"><label class="form-label small fw-semibold">Shop status</label><select class="form-select" name="status"><option value="">All statuses</option><?php foreach(['draft','active','suspended'] as $option): ?><option value="<?= e($option) ?>" <?= $status===$option?'selected':'' ?>><?= e(ucfirst($option)) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><button class="btn btn-primary w-100">Search</button></div></div></form>
 <div class="table-responsive"><table class="table platform-table align-middle mb-0"><thead><tr><th>Shop</th><th>Owner</th><th>Catalogue</th><th>Subscription</th><th>Status</th><th></th></tr></thead><tbody>
 <?php if(!$result['items']): ?><tr><td colspan="6"><div class="platform-empty">No shops match your search.</div></td></tr><?php endif; ?>
 <?php foreach($result['items'] as $row): ?><tr><td><div class="platform-shop"><div class="platform-shop-avatar"><?= e(strtoupper(substr((string)$row['name'],0,1))) ?></div><div><div class="fw-semibold"><?= e($row['name']) ?></div><div class="platform-muted">/<?= e($row['slug']) ?></div></div></div></td><td><div class="fw-semibold"><?= e(trim(($row['first_name']??'').' '.($row['last_name']??'')) ?: 'Merchant') ?></div><div class="platform-muted"><?= e($row['phone']??'') ?></div></td><td><span class="fw-semibold"><?= number_format((int)$row['product_count']) ?></span> <span class="platform-muted">products</span><div class="platform-muted"><?= number_format((int)$row['order_count']) ?> orders</div></td><td><?php if($row['plan_name']): ?><div class="fw-semibold"><?= e($row['plan_name']) ?></div><span class="status-badge <?= e(shopStatusClass($row['subscription_status'])) ?>"><?= e(ucwords(str_replace('_',' ',(string)$row['subscription_status']))) ?></span><?php else: ?><span class="platform-muted">Not subscribed</span><?php endif; ?></td><td><span class="status-badge <?= e(shopStatusClass($row['status'])) ?>"><?= e(ucfirst((string)$row['status'])) ?></span></td><td class="text-end"><a class="btn btn-sm btn-light border" href="<?= e(PlatformAuth::basePath()) ?>/shops/view/<?= (int)$row['id'] ?>">View</a></td></tr><?php endforeach; ?>
 </tbody></table></div>
 <?php if($result['pages']>1): ?><div class="p-3 border-top d-flex justify-content-between align-items-center"><span class="platform-muted">Page <?= $result['page'] ?> of <?= $result['pages'] ?></span><div class="platform-pagination d-flex gap-1"><?php if($result['page']>1): ?><a class="btn btn-sm btn-light border" href="?<?= http_build_query(['search'=>$search,'status'=>$status,'page'=>$result['page']-1]) ?>">Previous</a><?php endif; ?><?php if($result['page']<$result['pages']): ?><a class="btn btn-sm btn-light border" href="?<?= http_build_query(['search'=>$search,'status'=>$status,'page'=>$result['page']+1]) ?>">Next</a><?php endif; ?></div></div><?php endif; ?>
</section>
<?php $content=ob_get_clean(); $title='Shops'; $platformSection='shops'; require $root.'/app/Views/layouts/platform.php';
